CREATE TABLE AUTH (
  SEQ       NUMBER          NOT NULL PRIMARY KEY,
  ID        VARCHAR2(12)    NOT NULL UNIQUE,
  PASSWORD  VARCHAR2(12)    NOT NULL
);

CREATE SEQUENCE SEQ_AUTH INCREMENT BY 1 START WITH 1 NOCACHE;

COMMIT;
