CREATE TABLE CLOB_TABLE (
  SEQ      NUMBER                               NOT NULL,
  NAME     VARCHAR2(20)                         NOT NULL,
  CONTENT  CLOB,
  SUBJECT  VARCHAR2(400)
);

CREATE SEQUENCE SEQ_CLOB_TABLE
INCREMENT BY 1 START WITH 1 MINVALUE 1 NOCYCLE NOCACHE;

COMMIT;