CREATE TABLE MEMBER_INFO (
  FSEQ    NUMBER            NOT NULL,
  NAME    VARCHAR2(20)      NOT NULL,
  JUMIN1  CHAR(6)           NOT NULL,
  JUMIN2  CHAR(7)           NOT NULL,
  CONSTRAINT FK_MEMBER_INFO_FSEQ FOREIGN KEY (FSEQ)
    REFERENCES AUTH (SEQ)
);

CREATE UNIQUE INDEX UK_MEMBER_INFO_JUMIN ON MEMBER_INFO (JUMIN1, JUMIN2);

COMMIT;