<%-- header.jsp --%>
<!-- Generated by header.jsp -->
<CENTER><FONT SIZE=6><B>Java Power Group</B></FONT><BR>
<% DateFormat date = DateFormat.getDateInstance(DateFormat.LONG); %>
<%= date.format(new Date()) %>
</CENTER><HR>